name: Publish Docs

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: 16.x

      - name: Cache Dependencies
        id: cache-node
        uses: actions/cache@v2.1.7
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os}}-node-
      - name: Install Dependencies
        if: steps.cache-node.output.cache-hit != 'true'
        run: yarn install --frozen-lockfile --non-interactive --silent --prefer-offline

      - name: Build Docs
        run: yarn build

      - name: Commit Docs
        run: |
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]
          git diff-index --quiet HEAD || git commit -am "(Github Action): updated docs"
          git diff-index --quiet HEAD || git push origin main -f
